import type { Product } from "@/lib/types";

const SIZES = ["S", "M", "L", "XL", "2XL", "3XL"]; // TODO: confirm with Melissa

export const products: Product[] = [
  {
    slug: "good-girls-go-to-heaven",
    title: "Good Girls Go to Heaven",
    description: "TODO: description from her listing",
    price: 2400,
    images: ["/products/Good-girls-go-to-heaven-mock-up.png"],
    tags: ["sassy", "funny"],
    category: "everyday",
    sizes: SIZES,
    colors: ["TODO"],
    featured: true,
  },
  {
    slug: "hot-mess-doing-my-best",
    title: "Hot Mess Doing My Best",
    description: "TODO: description from her listing",
    price: 2400,
    images: ["/products/Hot-mess-doing-my-best-mock-up.png"],
    tags: ["funny", "relatable"],
    category: "everyday",
    sizes: SIZES,
    colors: ["TODO"],
    featured: true,
  },
  {
    slug: "im-not-judging-you-my-face-is",
    title: "I'm Not Judging You, My Face Is",
    description: "TODO: description from her listing",
    price: 2400,
    images: ["/products/Im-not-judging-you-my-face-is-mock-up.png"],
    tags: ["sarcastic", "funny"],
    category: "everyday",
    sizes: SIZES,
    colors: ["TODO"],
    featured: true,
  },
  {
    slug: "too-glam-to-give-a-damn",
    title: "Too Glam to Give a Damn",
    description: "TODO: description from her listing",
    price: 2400,
    images: ["/products/Too-glam-to-give-a-damn-mock-up.png"],
    tags: ["sassy", "glam"],
    category: "everyday",
    sizes: SIZES,
    colors: ["TODO"],
    featured: true,
  },
  {
    slug: "wild-heart-witchy-soul",
    title: "Wild Heart Witchy Soul",
    description: "TODO: description from her listing",
    price: 2400,
    images: ["/products/Wild-heart-witchy-soul-mock-up.png"],
    tags: ["witchy", "halloween", "fall"],
    category: "everyday",
    sizes: SIZES,
    colors: ["TODO"],
    featured: true,
  },
];